backend:
  namespace: konlateang-service-uat
  image: ghcr.io/kodlnw-software-house/konlateang-back-end
  tag: uat
  replicas: 1
  imagePullSecrets: konlateang-ghcr
  port: 3000
  healthCheckPath: "/health"
ingress:
  host: dev.kodlnw-product.net
  path: "/back-end(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
extraEnv:
  ENV_HOST: kodlnw-service-front-end-uat